import type { Metadata } from "next";
import { PageIntro } from "@/components/pages/intelligence-page";
import { StrategicSignals } from "@/components/dashboard/strategic-signals";
import { monthlyInsights } from "@/data/reports";
import { countries, trends } from "@/data/trends";

export const metadata: Metadata = { title: "월간 리포트" };

export default function MonthlyReportPage() {
  return <div className="shell page-shell"><PageIntro eyebrow="MONTHLY REPORT · 2026.08" title="월간 Robot Intelligence Dashboard" description="정책·시장·기술·국가·밸류체인 변화를 월간 관점에서 종합 분석합니다." stats={[{ label: "분석 동향", value: "40건" }, { label: "주요 시사점", value: "4개" }]} /><section className="monthly-metrics">{monthlyInsights.map((item) => <article key={item.title}><span>{item.title}</span><div><strong>{item.value}</strong><em>{item.unit}</em></div><b>{item.change}</b><p>{item.note}</p></article>)}</section><section className="monthly-grid"><div className="monthly-panel"><div className="section-header"><div><p className="eyebrow">COUNTRY MATRIX</p><h2>국가별 변화 강도</h2></div></div><div className="country-matrix">{countries.map((country) => { const items = trends.filter((item) => item.country === country); return <div key={country}><strong>{country}</strong><span>정책 {items.filter((i) => i.category === "policy").length}</span><span>산업 {items.filter((i) => i.category === "industry").length}</span><span>기술 {items.filter((i) => i.category === "technology").length}</span><i style={{ width: `${55 + items.filter((i) => i.importance === "A").length * 12}%` }} /></div>; })}</div></div><div className="monthly-panel"><div className="section-header"><div><p className="eyebrow">VALUE CHAIN</p><h2>밸류체인 압력 지점</h2></div></div><div className="value-chain"><div><span>01</span><strong>모델·데이터</strong><p>제조 특화 VLA와 학습 데이터 확보 경쟁</p></div><div><span>02</span><strong>핵심부품</strong><p>액추에이터 양산과 원가 하락 가속</p></div><div><span>03</span><strong>시스템 통합</strong><p>다기종 관제·안전 인증 역량 중요도 상승</p></div><div><span>04</span><strong>서비스 운영</strong><p>구독형 유지관리와 성과 데이터 확산</p></div></div></div></section><section className="section-block signal-section"><div className="section-header"><div><p className="eyebrow">STRATEGIC SIGNAL</p><h2>월간 변화 신호</h2><p>변화의 방향과 강도를 함께 판단합니다.</p></div></div><StrategicSignals /></section><section className="report-implication"><p className="eyebrow">EXECUTIVE IMPLICATION</p><h2>2026년 하반기, ‘양산 가능한 로봇 AI’가 핵심 경쟁 기준</h2><p>정책 지원과 민간 투자가 모델 개발을 넘어 부품 조달, 안전성 검증, 현장 운영으로 확장되고 있습니다. 국내 전략은 개별 요소기술 지원보다 수요 현장과 인증체계를 포함한 통합 실증에 우선순위를 둘 필요가 있습니다.</p><ol><li>휴머노이드 핵심부품의 공급망 리스크와 원가 추이를 월 단위로 점검</li><li>Robot Foundation Model의 안전성·현장성 평가기준 선점</li><li>공공조달 연계형 로봇 실증을 확산 경로로 활용</li></ol></section></div>;
}
